# Node docker image on which this would be run
image: node:latest
cache:
  paths:
    - node_modules/
stages:
  - test
  - deploy_production

# Job 1:
Test:
  stage: test
  only:
    - melting-frontend
  except:
    changes:
    - ".gitlab-ci.yml"
  script:
    - npm install

# Job 2:
# Deploy to staging
Development:
  image: ruby:latest
  only:
    - melting-frontend
  except:
    changes:
    - ".gitlab-ci.yml"
  stage: deploy_production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=melting-works-frontend --api-key=$HEROKU_API_KEY